<script lang="ts">
    import { page } from '$app/stores';

    const nhsNumber = $derived($page.url.searchParams.get('nhs_number'));
</script>

<div class="min-h-screen bg-gray-50 flex flex-col justify-center py-12 px-4">
    <div class="sm:mx-auto sm:w-full sm:max-w-md">
        <!-- Success Header -->
        <div class="text-center mb-8">
            <div class="inline-block bg-green-600 text-white px-6 py-3 mb-4">
                <h1 class="text-2xl font-bold">✓ REGISTRATION SUCCESSFUL</h1>
            </div>
            <p class="text-gray-600">Patient Record Created</p>
        </div>

        <!-- Success Container -->
        <div class="bg-white border-4 border-green-600 p-8">
            <div class="text-center">
                <svg class="w-16 h-16 text-green-600 mx-auto mb-4" fill="currentColor" viewBox="0 0 20 20">
                    <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd" />
                </svg>

                <h2 class="text-2xl font-bold text-gray-900 mb-4">Patient Successfully Registered</h2>

                <div class="bg-blue-50 border-2 border-blue-600 p-6 mb-6">
                    <p class="text-sm text-gray-600 mb-2">New NHS Number (AC 7.1):</p>
                    <p class="text-3xl font-bold text-gray-900 font-mono">{nhsNumber || 'N/A'}</p>
                    <p class="text-xs text-gray-500 mt-3">
                        ✓ Unique identifier auto-generated by system
                    </p>
                </div>

                <div class="bg-green-50 border-l-4 border-green-600 p-4 mb-6 text-left">
                    <p class="font-bold text-green-900 mb-2">Story 07 Acceptance Criteria:</p>
                    <ul class="space-y-1 text-sm text-green-800">
                        <li>✓ AC 7.1: Unique NHS number generated successfully</li>
                        <li>✓ AC 7.2: DOB validation enforced (no future dates)</li>
                        <li>✓ Patient record persisted to database</li>
                        <li>✓ Audit log entry created for GDPR compliance</li>
                        <li>✓ Password hashed with bcrypt (NFR1)</li>
                    </ul>
                </div>

                <p class="text-sm text-gray-600 mb-6">
                    Patient can now use this NHS Number <span class="font-mono bg-gray-100 px-2 py-1">{nhsNumber}</span> to log in.
                </p>

                <div class="flex gap-3">
                    <a href="/" class="flex-1 bg-blue-600 text-white px-6 py-4 font-bold hover:bg-blue-700 transition-colors">
                        ← Back to Login
                    </a>
                    <a href="/admin/register" class="flex-1 bg-gray-900 text-white px-6 py-4 font-bold hover:bg-gray-800 transition-colors">
                        Register Another →
                    </a>
                </div>
            </div>
        </div>

        <!-- Info Panel -->
        <div class="mt-6 bg-white border border-gray-300 p-4 text-sm text-gray-600">
            <p class="font-bold mb-2">Test the New Patient:</p>
            <ul class="space-y-1">
                <li>1. Note the NHS Number displayed above</li>
                <li>2. Go back to login page</li>
                <li>3. Enter this NHS Number and password you set</li>
                <li>4. Click "ACCESS PATIENT PORTAL"</li>
            </ul>
        </div>
    </div>
</div>
